# src/main/resources/application.properties
spring:
  application:
  name: customer
  datasource:
  url: jdbc:h2:mem:testdb
  driverClassName: org.h2.Driver
  username: sa
  password: password
  h2:
  console:
  enabled: true
  ddl-auto: update

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs